language: java
jdk:
  - openjdk11

branches:
  only:
    - master

addons:
  sonarcloud:
    organization: "labadi0"

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=labadi0_learnTravisCi
  #- mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=labadi0_learnTravisCi
  - mvn clean install sonar:sonar -Dsonar.projectKey=labadi0_IT_SCANNER

services:
  - mysql
before_install:
  - chmod +x mvnw
