language: java
jdk:
  - openjdk11

branches:
  only:
    - master

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=labadi0_learnTravisCi
  #- mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=labadi0_learnTravisCi
  - mvn clean install sonar:sonar -Dsonar.projectKey=labadi0_IT_SCANNER
  #- mvn sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths=$(find "$(pwd)" -path '*jacoco.xml' | sed 's/.*/&/' | tr '\n' ',').projectKey=labadi0_learnTravisCi
  #- mvn clean install sonar:sonar -Dsonar.projectKey=labadi0_learnTravisCi
services:
  - mysql
before_install:
  - chmod +x mvnw
