language: java
jdk:
  - openjdk11

branches:
  only:
    - master

addons:
  sonarcloud:
    organization: "labadi0"

script:
  - mvn clean install sonar:sonar -Dsonar.projectKey=labadi0_IT_SCANNER
services:
  - mysql
before_install:
  - chmod +x mvnw

notifications:
  email: labaditarekk@gmail.com
  #webhooks: https://discord.com/api/webhooks/916116768731303957/XC4hl_xUqxWh29O3YmbXTI-nfVlLYt2xnBBSACRo2Lgl8N3s69dsxOjxDe4Sqi_mU4AH
